### ISSUE TITLE
Buy License button didn't work

### ISSUE THREAD

**Issue by mdavydau** [harbur/kubernetic#339] opened 2022-02-24 14:17 UTC
I bought my non-expiration license 2 years ago, and there shouldn't be an expiration time. For now, the application asks me to renew my license. 
Looks like kubernetic team changed their pricing policy and now forces me to buy a new license.
Yes, also the button didn't work.

**Comment by dkapanidis** [comment] 2022-02-24 15:07
Hi, 

The change has been explained in more details in the blog post [here](https://www.kubernetic.com/blog/release-3-3-0). This is a needed step for a more sustainable app development and is part of new app development which will be released as Kubernetic v4.

You can continue using Kubernetic v3.2.0 ([Mac](https://kubernetic.s3.amazonaws.com/Kubernetic-3.2.0.dmg), [Linux](https://kubernetic.s3.amazonaws.com/Kubernetic-3.2.0.AppImage), [Win](https://kubernetic.s3.amazonaws.com/Kubernetic+Setup+3.2.0.exe)) without any limitations.
The licensing change only apply on the renewed development which takes place since v3.3.0.

For all existing clients there is a discount of 20% for any number of licenses for the until end of March, to request simply send an email at [contact@harbur.io](mailto:contact@harbur.io?subject=Discount%20offer).

---

Can you describe in more detail about the button that didn't work.

* Are you referring to the button in the Desktop App? If so, which OS are you using? Is your Desktop version 3.3.0? What is it doing?

* Are you referring to the web button "Next" which redirects to Stripe payment gateway? This takes 1-2 secs as it prepares the payment session. If so are you on the Individual or Organization payment? Did you fill-in Tax ID on organization?

**Comment by poom** [comment] 2022-02-24 17:51
Yes `Buy License` button in Mac OS Desktop v3.3.0 doesn't work

**Comment by mdavydau** [comment] 2022-02-25 09:45
macOS Monterey Desktop v3.3.0

**Comment by dkapanidis** [comment] 2022-02-25 11:43
That's odd. The button opens this URL: https://www.kubernetic.com/pricing on your default browser. More specifically the following command is executed:

```sh
open https://www.kubernetic.com/pricing
```

Is it possible you don't have a default browser configured on your OS:

<img width="655" alt="Screenshot 2022-02-25 at 12 42 42" src="https://user-images.githubusercontent.com/367397/155709565-0ae4f1f3-a4e1-4c06-b072-c933395d7064.png">


and the effect is this:

![2022-02-25 12 33 14](https://user-images.githubusercontent.com/367397/155708751-2f770447-d2d6-49c2-af8d-1546004a8c91.gif)

**Comment by bfgits** [comment] 2022-04-14 03:58
the license with "unlimited app updates"  means for nothing for your customers

checkout https://web.archive.org/web/20200414140642/https://kubernetic.com/

**Comment by dkapanidis** [comment] 2022-04-14 11:23
@bfgits read [here](https://github.com/harbur/kubernetic/issues/346#issuecomment-1092763074) for more details regarding the licensing and the 50% active discount that is offered for Kubernetic 2 users.

I'm closing this issue as I can't reproduce the problem with the "Buy License" button.

**Closed by dkapanidis** 2022-04-14 11:23 UTC
