### ISSUE TITLE
Update not working on MacOs

### ISSUE THREAD

**Issue by djakielskiadesso** [harbur/kubernetic#237] opened 2020-09-17 08:14 UTC
I've got an message for the latest version is availiable. When i confirm, the dialog close an nothing is gonna happend. I could do this again and again. Update work only with an manuell download and update.

My Version: 2.11.1

I love the idea and design of this tool, but the software qualitity is terrible and very frustrating. Since i paid for a licence, i expect more quality and less less bugs.

**Comment by djakielskiadesso** [comment] 2020-09-17 08:17
Update:
After waiting about 5 minutes, i got this error message:
![grafik](https://user-images.githubusercontent.com/52488859/93439456-e0ff4a80-f8ce-11ea-94d1-bd1259285060.png)

My internet connections works fine and no proxy was used.

**Comment by JuankaHarbur** [comment] 2020-09-17 09:00
Thank you. We are reviewing the problem, we will give you an answer shortly.

**Comment by JuankaHarbur** [comment] 2020-09-17 11:49
The error was because there were two simultaneous calls, this causes a conflict. For the next release it will be solved. Thank you very much for your help

**Comment by dkapanidis** [comment] 2020-09-17 11:53
just to clarify, the update process works ok, the problem is triggered when a new update is triggered when an update is still in-flight, we're resolving this for next release to be avoided.

**Closed by dkapanidis** 2020-09-17 11:53 UTC
