### ISSUE TITLE
it just freezes

### ISSUE THREAD

**Issue by masterkain** [harbur/kubernetic#120] opened 2019-10-29 06:30 UTC
1) freezes
2) more freezes
3) blank windows
4) no helm 3
5) freezes
6) no binaries in PATH
7) freezes
8) no helm 2
9) freezes

from essential to unusable

**Comment by dcagnetta** [comment] 2019-10-31 12:20
same here, have uninstalled it

**Comment by AlexandreCassagne** [comment] 2019-11-18 20:22
Same issue here.

**Comment by spiddy** [comment] 2019-11-18 20:41
Can you please provide some info on your system that may help pinpoint the issue:

- Which operating system (Win, Linux, Mac)?
- Which version of Kubernetic did you try?
- Where does it freeze? is it on the startup or on some specific action?
- Which kubernetes stack are you using? A specific cloud provider or an on-premise vendor?
- Is your kubectl configured properly on the same machine? Do you use the `~/.kube/config` file for configuration or a different file by ENV variable?
- Is there any proxy between the machine and the cluster?

**Comment by AlexandreCassagne** [comment] 2019-11-19 20:03
**Which operating system (Win, Linux, Mac)?**

Mac.

**Which version of Kubernetic did you try?**

v2.4.1

**Where does it freeze? is it on the startup or on some specific action?**

Randomly, after inactivity (5 seconds), after opening logs, after switching the context...

Which kubernetes stack are you using? A specific cloud provider or an on-premise vendor?

Google Cloud Kubernetes engine, not customised.

Is your kubectl configured properly on the same machine? Do you use the ~/.kube/config file for 
configuration or a different file by ENV variable?

Kubectl works fine, and I use the ~/.kube/config file.

Is there any proxy between the machine and the cluster?

I believe not. I use the standard method of connecting to GKE.

**Comment by bilus** [comment] 2019-11-21 13:18
Same here. Liked it, froze twice in the past 10 minutes, am probably going to uninstall it.

**Comment by mrkswrnr** [comment] 2019-11-29 14:28
Same for me when viewing pod logs. Seems to happen when container state is "terminated"

**Comment by Merlz** [comment] 2019-11-30 08:39
Confirmed the same when viewing logs and a container is terminated, freezes up completely and must be quit from the menu (Command Q has no affect)

**Comment by Rostislaved** [comment] 2019-12-13 15:29
same. MacOS 2.4.1

**Comment by Basster** [comment] 2019-12-19 09:37
Same here, mostly when viewing logs. But I'm okay with a quick restart, because it shines on so many other ends! 

Ubuntu 18.04, GKE via `~/.kube/config`

**Comment by Bnjmn83** [comment] 2020-01-08 21:17
Happens to me when viewing logs. Needs restart. Unusable.

**Comment by mrkswrnr** [comment] 2020-01-22 12:40
This seems to be fixed in v2.4.2. Thank you!

**Comment by dkapanidis** [comment] 2020-02-22 11:52
The freezing issue is fixed in release v2.4.2.

The "show last x lines" is fixed in v2.5.0, along with other improvements on the logs page.

**Closed by dkapanidis** 2020-02-22 11:52 UTC
