### ISSUE TITLE
The list is not updated after deleting a resource. Very annoying.

### ISSUE THREAD

**Issue by stepanselyuk** [harbur/kubernetic#162] opened 2020-05-26 11:16 UTC
Hello,
I use the paid version, 2.7.0

The list is not updated after deleting a resource. Very annoying. It updates actually, but the wrong item missing and deleted resource remains on the list.

**Comment by dkapanidis** [comment] 2020-06-09 09:09
Hi,

Can you provide some more details about the issue?

- Steps to reproduce the issue (e.g. which kind of resource did you try to delete?)
- Is the issue reproduced every time?

I believe the issue was due to some networking disconnection. I describe  a bit more about it and how it will be improved in the next release [here](https://medium.com/@dimitris.kapanidis/hi-krzysztof-f8bdfdb8e802)

> About refreshing, until now Kubernetic is using namespace watching mechanism, which opens one websocket for all resources updates. If that socket breaks (e.g. network disconnect) there is no deadman switch to reconnect, which is responsible for those strange situations of disconnection. on 0.8.0 there is a refresh button at the top side menu (left of the context dropdown) that manually reconnects, but on next release we're working on using react-query to trigger fetch/watch of resources per page, which provides a very nice UI experience (it's already used on Helm 3 pages) because it provides a cache, automatic failure retries and background refresh, while also displaying visually loading status.

**Comment by dkapanidis** [comment] 2020-07-14 06:56
fixed on v2.9.0

Now each page is doing separate requests to the backend to retrieve the items, and opens a dedicated watch websocket for real-time changes.

**Closed by dkapanidis** 2020-07-14 06:56 UTC
