### ISSUE TITLE
Log into the pod

### ISSUE THREAD

**Issue by inikolaev** [harbur/kubernetic#126] opened 2020-01-09 12:35 UTC
Would be really nice to be able to log into a shell for a specific pod.

**Comment by s1rc** [comment] 2020-01-15 20:43
Seconded!

**Comment by inikolaev** [comment] 2020-01-26 21:58
I created a simple Electron app to solve this specific problem for me: https://github.com/inikolaev/get-kubernetes-desktop-client

**Comment by dkapanidis** [comment] 2020-04-13 12:24
duplicate of #45

**Closed by dkapanidis** 2020-04-13 12:24 UTC
