### ISSUE TITLE
[Feature request] Copying your clipboard into the Terminal

### ISSUE THREAD

**Issue by Sonorpearl** [harbur/kubernetic#172] opened 2020-07-09 09:47 UTC
I would love to request the ability to copy your clipboard into the Kubernetic Terminal. Currently, it does not work under Windows at least. Can work either with Control + V or just with a Rightclick as any other Terminals do. :-)
The ability to mark a text and right-click (Or Control + C) to save something to your clipboard would also be nice.
Thanks in advance.

**Comment by dkapanidis** [comment] 2020-07-09 09:54
thanks for feedback,

this is duplicate of #169, please upvote that one to centralize requests.

**Closed by dkapanidis** 2020-07-09 09:54 UTC
