### ISSUE TITLE
Bring back "quick action" buttons for deployments, etc. 

### ISSUE THREAD

**Issue by pinkfloydx33** [harbur/kubernetic#359] opened 2022-05-22 12:01 UTC
One of the recent updates (which are great btw!) removed the "quick action" buttons when viewing a deployment. I'm referring to the restart/scaleup/scaledown buttons that used to be listed **inline within the table/rows** display. In order to restart or scale I must now drill down into a deployment, click the actions menu drop down, find the action in the list and then click it.

Whereas before everything was readily available on one screen and could be invoked with a single click, I now need to perform 3 distinct actions and then a fourth to return to the original list.

Usability is definitely suffering a bit as is my personal productivity. Since I've been using kubernetic for years, my muscle memory is getting the best of me. I even find this to be an issue once drilled into a deployment as the buttons used to be there as well (granted they still are via the drop-down, but I must go searching)

Any way we can get these (and any like them) back?

**Comment by dkapanidis** [comment] 2022-05-22 12:08
Hi, thanks for the feedback will take it into account for next iterations.

The changes is certainly somehow disruptive, but for good measure, the quick actions on the right side is limited in space. They are replaced by a context menu which opens when you right click on the row.

![context-menu](https://user-images.githubusercontent.com/367397/169694344-81d21ea7-79f0-4bcf-96f3-941eb2700e1b.gif)

Please let me know if this solves the productivity issue, also I'm actively adding keyboard shortcuts to boost productivity. Rows can be selected with keyboard and a shortcut can be added to scale up/down & restart.

Maybe the issue is the discoverability of those options and not the lack of the previous quick-actions button. What do you think?

**Comment by dkapanidis** [comment] 2022-05-22 12:15
> The changes is certainly somehow disruptive, but for good measure, the quick actions on the right side is limited in space.

As follow-up, I'm planning to also add more resource-related actions to the context-menu such as view logs, port forward ports, open terminal, view events, undo rollout directly from the resources table, without need to drill-down. These were not possible with previous quick actions as the space were limited.

Maybe a `⋮` button can appear at the right side when hovering on a row for discovery.

**Comment by pinkfloydx33** [comment] 2022-05-22 13:55
Omg. I completely missed the right click context menu. I'll have to try it out and report back.

One issue with either approach is that previously with the buttons, I could rapidly scale up or down by spam clicking the buttons. This is no longer possible. Keyboard shortcuts could work I suppose

**Comment by pinkfloydx33** [comment] 2022-05-22 14:25
Context menu works, I can get used to it. I'm not sure how to make it more discoverable though. I should probably read the release notes more carefully. Feel free to close. Thanks.

**Comment by mrjamiebowman** [comment] 2022-06-06 20:36
I strongly want those buttons back in addition to the context-menu.

The context-menu needs a "Scale to" option as well. Imagine you have 10 or 20 pods running. It's not easy to scale down.. we would spam the scale up/down buttons. The buttons as they were are very desirable especially for dev environments where we may scale down more frequently. Strongly want that back.

**Comment by mrjamiebowman** [comment] 2022-06-14 16:25
> Hi, thanks for the feedback will take it into account for next iterations.
> 
> The changes is certainly somehow disruptive, but for good measure, the quick actions on the right side is limited in space. They are replaced by a context menu which opens when you right click on the row.
> 
> ![context-menu](https://user-images.githubusercontent.com/367397/169694344-81d21ea7-79f0-4bcf-96f3-941eb2700e1b.gif) [ ](https://user-images.githubusercontent.com/367397/169694344-81d21ea7-79f0-4bcf-96f3-941eb2700e1b.gif) ![context-menu](https://user-images.githubusercontent.com/367397/169694344-81d21ea7-79f0-4bcf-96f3-941eb2700e1b.gif) [ ](https://user-images.githubusercontent.com/367397/169694344-81d21ea7-79f0-4bcf-96f3-941eb2700e1b.gif)
> 
> Please let me know if this solves the productivity issue, also I'm actively adding keyboard shortcuts to boost productivity. Rows can be selected with keyboard and a shortcut can be added to scale up/down & restart.
> 
> Maybe the issue is the discoverability of those options and not the lack of the previous quick-actions button. What do you think?

Make it an option? My screen resolution is big enough that this isn't a problem for me.

**Comment by mrjamiebowman** [comment] 2022-06-28 21:57
Saw with the latest release there were "+" and "-".. I liked the buttons that works too! Great addition! :)

**Comment by Borvik** [comment] 2022-07-06 12:33
I found them in the context menu - not sure I like the extra click.

Screen resolution and size is large enough for the column for me, and having single click access as I manage deployments was one of the awesome features of kubernetic.

I can understand trying to optimize for screen real-estate, but maybe like mrjamiebowman suggested - make the column an optional setting for those that want it - a setting that persists so we don't have to enable the column every time we open the application.

**Comment by dkapanidis** [comment] 2022-07-06 12:38
@Borvik have you discovered the shortcut keys for the same actions? (`+`, `-`, `r`). They are shown on the context menu. Aren't those a faster access to the actions than column actions. Just want to make sure this is actually needed instead of being inertia to status quo.

**Comment by Borvik** [comment] 2022-07-06 12:43
I did discover those yes, and while that's an improvement over only having the context menu - I still think the column would be nicer.

I've known some admins that are mouse-click admins and need UIs, but are otherwise just as capable - and other admins that are keyboard purists. (I'm probably a mix of the UI and keyboard admin)

**Comment by mrjamiebowman** [comment] 2022-07-07 14:02
Could always make it a UI feature so it can be toggled on and off... and I strongly think we should be able to click a context menu button to "Scale To"..

**Comment by mrjamiebowman** [comment] 2022-07-21 13:27
Wow! Rockstar status! That's a really good idea.

**Comment by Borvik** [comment] 2022-07-21 15:00
Great! Best of both, without even needing a setting.

**Comment by pinkfloydx33** [comment] 2022-07-21 23:02
Looks great. Thanks for taking the time on this one.

**Comment by pinkfloydx33** [comment] 2022-08-09 11:53
Hovering off the window causes the icons to stay on the last row you hovered over, making it impossible to see what's underneath. Not a big a deal with multiple rows since you could just hover to a different one, but if there's only one row there's not much for the user to do.

You can see the behavior in your video. I just noticed it after installing the update. Not sure if it's a bug or working as intended or what but figured I'd call it out just in case

**Comment by dkapanidis** [comment] 2022-08-09 12:03
v4.4.0 released with quick actions 🥳

@pinkfloydx33 noted, as workaround you can unselect by clicking in the screen, closing as there is workaround to focus on other areas.

**Closed by dkapanidis** 2022-08-09 12:03 UTC

**Comment by dkapanidis** [comment] 2022-08-09 12:40
Fixed the issue (will be on next release though).

![2022-08-09 14 37 26](https://user-images.githubusercontent.com/367397/183648811-fde379c8-f6eb-4058-adce-b897ab6e8dc5.gif)

Instead of using group-focus I'm now using group-hover to handle the visibility of the quick actions. The focus is also used by keyboard navigation, you can see the video the distinction. Now when not hovered the quick actions are not visible anymore.
